[toolchain.rust]
ext = "rs"
run = "cargo run --color always {args}"
dir = "{day}"
[toolchain.rust.compile]
build = "cargo build --release"
execute = "{day}/target/release/{name:day}"

[toolchain.python]
ext = "py"
run = "python3 {file}"
[toolchain.python.compile]
execute = "python3 {file}"
